const CREATE_USER = 'USER/CREATE'
const UPLOAD_LOCAL_IMG = 'ADD-PRROPERTY/UPLOAD_LOCAL_ING'
const APPEND_USERS_ID = 'USERS/CARD/ADD_IDS'
const REMOVE_USERS_ID = 'USERS/CARD/REMOVE_IDS'

export { CREATE_USER, UPLOAD_LOCAL_IMG, APPEND_USERS_ID, REMOVE_USERS_ID }
